/**
 * @description Test data generator for QuDAG Executive Intelligence Center
 * @author CleoClaudeDesktop
 * @created 2025-06-23
 * @lastModified 2025-06-23 by CleoClaudeDesktop - Test data for demo
 */

export const testOrganizations = [
  {
    id: 'demo-org-1',
    tenant_id: 'tenant-demo-1',
    name: 'QuDAG Enterprises',
    logo_url: 'https://via.placeholder.com/64',
    industry: 'Technology',
    size: 'enterprise' as const,
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date().toISOString(),
    settings: {
      theme: 'dark' as const,
      language: 'en',
      timezone: 'UTC',
      features: {
        voice_commands: true,
        predictive_analytics: true,
        auto_scaling: true,
      },
    },
    metadata: {
      industry_segment: 'ai_automation',
      employee_count: 150,
    },
  },
];

export const testDepartments = [
  {
    id: 'dept-1',
    organization_id: 'demo-org-1',
    name: 'AI Operations',
    type: 'operations' as const,
    parent_id: null,
    manager_agent_id: null,
    budget_allocation: 500000,
    created_at: new Date('2024-02-01').toISOString(),
    metadata: { focus: 'automation' },
  },
  {
    id: 'dept-2',
    organization_id: 'demo-org-1',
    name: 'Revenue Generation',
    type: 'sales' as const,
    parent_id: null,
    manager_agent_id: null,
    budget_allocation: 750000,
    created_at: new Date('2024-02-01').toISOString(),
    metadata: { focus: 'growth' },
  },
  {
    id: 'dept-3',
    organization_id: 'demo-org-1',
    name: 'R&D Innovation',
    type: 'r&d' as const,
    parent_id: null,
    manager_agent_id: null,
    budget_allocation: 300000,
    created_at: new Date('2024-02-01').toISOString(),
    metadata: { focus: 'research' },
  },
];

export const testAgents = [
  {
    agent_id: 'agent-001-exec',
    organization_id: 'demo-org-1',
    department_id: 'dept-1',
    business_role: 'Chief AI Officer',
    title: 'Executive AI Agent',
    level: 'executive' as const,
    personality_type: 'analyst' as const,
    personality_traits: {
      speed: 95,
      accuracy: 98,
      creativity: 85,
      collaboration: 90,
    },
    cost_per_hour: 250.00,
    hired_at: new Date('2024-03-01').toISOString(),
    last_active: new Date().toISOString(),
    status: 'active' as const,
    performance_rating: 4.8,
    custom_settings: { priority_level: 'critical' },
    metadata: { specialization: 'strategic_planning' },
  },
  {
    agent_id: 'agent-002-sales',
    organization_id: 'demo-org-1',
    department_id: 'dept-2',
    business_role: 'Revenue Optimizer',
    title: 'Sales AI Agent',
    level: 'manager' as const,
    personality_type: 'hunter' as const,
    personality_traits: {
      speed: 92,
      accuracy: 87,
      creativity: 78,
      collaboration: 85,
    },
    cost_per_hour: 180.00,
    hired_at: new Date('2024-03-15').toISOString(),
    last_active: new Date(Date.now() - 2 * 60 * 1000).toISOString(), // 2 min ago
    status: 'active' as const,
    performance_rating: 4.6,
    custom_settings: { target_focus: 'revenue_growth' },
    metadata: { specialization: 'sales_automation' },
  },
  {
    agent_id: 'agent-003-ops',
    organization_id: 'demo-org-1',
    department_id: 'dept-1',
    business_role: 'Operations Manager',
    title: 'Operations AI Agent',
    level: 'specialist' as const,
    personality_type: 'executor' as const,
    personality_traits: {
      speed: 88,
      accuracy: 94,
      creativity: 65,
      collaboration: 92,
    },
    cost_per_hour: 120.00,
    hired_at: new Date('2024-04-01').toISOString(),
    last_active: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 min ago
    status: 'active' as const,
    performance_rating: 4.4,
    custom_settings: { automation_level: 'high' },
    metadata: { specialization: 'process_optimization' },
  },
  {
    agent_id: 'agent-004-research',
    organization_id: 'demo-org-1',
    department_id: 'dept-3',
    business_role: 'Research Analyst',
    title: 'R&D AI Agent',
    level: 'specialist' as const,
    personality_type: 'analyst' as const,
    personality_traits: {
      speed: 75,
      accuracy: 96,
      creativity: 95,
      collaboration: 80,
    },
    cost_per_hour: 150.00,
    hired_at: new Date('2024-04-15').toISOString(),
    last_active: new Date(Date.now() - 10 * 60 * 1000).toISOString(), // 10 min ago
    status: 'active' as const,
    performance_rating: 4.7,
    custom_settings: { research_depth: 'comprehensive' },
    metadata: { specialization: 'innovation' },
  },
  {
    agent_id: 'agent-005-support',
    organization_id: 'demo-org-1',
    department_id: 'dept-2',
    business_role: 'Customer Success Agent',
    title: 'Support AI Agent',
    level: 'operator' as const,
    personality_type: 'farmer' as const,
    personality_traits: {
      speed: 85,
      accuracy: 90,
      creativity: 70,
      collaboration: 95,
    },
    cost_per_hour: 80.00,
    hired_at: new Date('2024-05-01').toISOString(),
    last_active: new Date(Date.now() - 1 * 60 * 1000).toISOString(), // 1 min ago
    status: 'active' as const,
    performance_rating: 4.2,
    custom_settings: { response_style: 'empathetic' },
    metadata: { specialization: 'customer_care' },
  },
  {
    agent_id: 'agent-006-maint',
    organization_id: 'demo-org-1',
    department_id: 'dept-1',
    business_role: 'System Maintenance',
    title: 'Maintenance AI Agent',
    level: 'operator' as const,
    personality_type: 'executor' as const,
    personality_traits: {
      speed: 90,
      accuracy: 99,
      creativity: 45,
      collaboration: 70,
    },
    cost_per_hour: 100.00,
    hired_at: new Date('2024-05-15').toISOString(),
    last_active: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 min ago
    status: 'maintenance' as const,
    performance_rating: 4.5,
    custom_settings: { maintenance_schedule: 'weekly' },
    metadata: { specialization: 'system_health' },
  },
];

export const testMetrics = [
  {
    id: 'metric-1',
    organization_id: 'demo-org-1',
    metric_type: 'revenue' as const,
    metric_subtype: 'monthly_recurring',
    value: 145000,
    currency: 'USD',
    period_start: new Date('2024-06-01').toISOString(),
    period_end: new Date('2024-06-30').toISOString(),
    department_id: 'dept-2',
    agent_id: null,
    created_at: new Date('2024-07-01').toISOString(),
    metadata: { source: 'automated_sales' },
  },
  {
    id: 'metric-2',
    organization_id: 'demo-org-1',
    metric_type: 'costs' as const,
    metric_subtype: 'operational',
    value: 85000,
    currency: 'USD',
    period_start: new Date('2024-06-01').toISOString(),
    period_end: new Date('2024-06-30').toISOString(),
    department_id: 'dept-1',
    agent_id: null,
    created_at: new Date('2024-07-01').toISOString(),
    metadata: { source: 'ai_operations' },
  },
  {
    id: 'metric-3',
    organization_id: 'demo-org-1',
    metric_type: 'efficiency' as const,
    metric_subtype: null,
    value: 0.87,
    currency: 'USD',
    period_start: new Date('2024-06-01').toISOString(),
    period_end: new Date('2024-06-30').toISOString(),
    department_id: null,
    agent_id: null,
    created_at: new Date('2024-07-01').toISOString(),
    metadata: { measurement: 'task_completion_rate' },
  },
  {
    id: 'metric-4',
    organization_id: 'demo-org-1',
    metric_type: 'profit' as const,
    metric_subtype: null,
    value: 60000,
    currency: 'USD',
    period_start: new Date('2024-06-01').toISOString(),
    period_end: new Date('2024-06-30').toISOString(),
    department_id: null,
    agent_id: null,
    created_at: new Date('2024-07-01').toISOString(),
    metadata: { calculation: 'revenue_minus_costs' },
  },
];

export const testProjects = [
  {
    id: 'proj-1',
    organization_id: 'demo-org-1',
    name: 'AI Customer Service Automation',
    description: 'Deploy autonomous customer service agents with 24/7 availability',
    status: 'active' as const,
    department_id: 'dept-2',
    lead_agent_id: 'agent-005-support',
    budget_allocated: 120000,
    budget_spent: 75000,
    start_date: new Date('2024-04-01').toISOString(),
    target_date: new Date('2024-08-15').toISOString(),
    success_metrics: {
      customer_satisfaction: 0.92,
      response_time_reduction: 0.78,
      cost_savings: 45000,
    },
    assigned_agents: ['agent-005-support', 'agent-002-sales'],
    created_at: new Date('2024-03-25').toISOString(),
    updated_at: new Date().toISOString(),
    metadata: { priority: 'high', category: 'automation' },
  },
  {
    id: 'proj-2',
    organization_id: 'demo-org-1',
    name: 'Revenue Optimization Engine',
    description: 'AI-powered pricing and sales optimization system',
    status: 'active' as const,
    department_id: 'dept-2',
    lead_agent_id: 'agent-002-sales',
    budget_allocated: 200000,
    budget_spent: 180000,
    start_date: new Date('2024-03-01').toISOString(),
    target_date: new Date('2024-07-30').toISOString(),
    success_metrics: {
      revenue_increase: 0.23,
      conversion_rate: 0.34,
      deal_velocity: 0.15,
    },
    assigned_agents: ['agent-002-sales', 'agent-001-exec'],
    created_at: new Date('2024-02-20').toISOString(),
    updated_at: new Date().toISOString(),
    metadata: { priority: 'critical', category: 'revenue' },
  },
  {
    id: 'proj-3',
    organization_id: 'demo-org-1',
    name: 'Quantum-Resistant Infrastructure',
    description: 'Upgrade all systems with post-quantum cryptography',
    status: 'planning' as const,
    department_id: 'dept-3',
    lead_agent_id: 'agent-004-research',
    budget_allocated: 500000,
    budget_spent: 25000,
    start_date: new Date('2024-09-01').toISOString(),
    target_date: new Date('2025-03-01').toISOString(),
    success_metrics: {
      security_compliance: 1.0,
      performance_impact: 0.05,
      migration_success: 0.98,
    },
    assigned_agents: ['agent-004-research', 'agent-003-ops', 'agent-006-maint'],
    created_at: new Date('2024-06-01').toISOString(),
    updated_at: new Date().toISOString(),
    metadata: { priority: 'high', category: 'security' },
  },
  {
    id: 'proj-4',
    organization_id: 'demo-org-1',
    name: 'Predictive Maintenance System',
    description: 'AI-driven predictive maintenance for all operational systems',
    status: 'completed' as const,
    department_id: 'dept-1',
    lead_agent_id: 'agent-006-maint',
    budget_allocated: 80000,
    budget_spent: 78000,
    start_date: new Date('2024-01-15').toISOString(),
    target_date: new Date('2024-05-15').toISOString(),
    completion_date: new Date('2024-05-10').toISOString(),
    success_metrics: {
      downtime_reduction: 0.67,
      maintenance_cost_savings: 0.34,
      prediction_accuracy: 0.91,
    },
    assigned_agents: ['agent-006-maint', 'agent-003-ops'],
    created_at: new Date('2024-01-10').toISOString(),
    updated_at: new Date('2024-05-10').toISOString(),
    metadata: { priority: 'medium', category: 'operations' },
  },
];